adding dBank to portfolio
Faudrey28/resume-react pull request #3
Opened 2022-08-12 22:12 UTC by Faudrey28

2022-08-15 03:30 UTC, Faudrey28 commented
Added dbank project page and modified contact logo links.

2022-08-22 00:57 UTC, jbiral commented on components/Main.jsx
> +                      <FaGithub />
This tag doesn't look aligned the same way others are on the page. Could you beautify the code one more time?

2022-08-22 01:02 UTC, jbiral requested changes

2022-08-22 01:02 UTC, jbiral commented on pages/dbank.js
> +          This is a DeFi Project, where a bank called dbank is build with its functionality for depositing, withdrawing and compounding the money.</p>
nit: built

2022-08-22 01:02 UTC, jbiral commented on pages/dbank.js
> +          This is a DeFi Project, where a bank called dbank is build with its functionality for depositing, withdrawing and compounding the money.</p>
In the same pull request, I see dBank, DBANK and dbank. It would be great to capitalize it the same way across the pull website.

2022-08-22 01:02 UTC, jbiral commented on pages/dbank.js
> +          <a href="https://github.com/Faudrey28/" target="_blank">
Reminder to update the link once it's pushed to GitHub

2022-08-24 03:16 UTC, merged